// <auto-generated />
using System;
using Dotnet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dotnet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220722074637_FewMoreStudent")]
    partial class FewMoreStudent
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Dotnet.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Address = "Delhi",
                            Name = "Ramesh Kumar"
                        },
                        new
                        {
                            Id = 102,
                            Address = "Aurangabad",
                            Name = "Raja Kumar"
                        },
                        new
                        {
                            Id = 103,
                            Address = "Dehri",
                            Name = "Ramesh Kumar"
                        },
                        new
                        {
                            Id = 104,
                            Address = "Gaya",
                            Name = "Lalita Kumari"
                        },
                        new
                        {
                            Id = 105,
                            Address = "Patna",
                            Name = "Ramesh Kumar"
                        },
                        new
                        {
                            Id = 106,
                            Address = "Hyderabad",
                            Name = "Ramesh Kumar"
                        },
                        new
                        {
                            Id = 107,
                            Address = "Chennai",
                            Name = "Rahim Khan"
                        },
                        new
                        {
                            Id = 108,
                            Address = "Orisha",
                            Name = "Rajesh Khanna"
                        },
                        new
                        {
                            Id = 109,
                            Address = "Bihar",
                            Name = "Sanjay Kumar"
                        },
                        new
                        {
                            Id = 110,
                            Address = "Varanashi",
                            Name = "Ramesh Kumar"
                        },
                        new
                        {
                            Id = 111,
                            Address = "Pune",
                            Name = "Shivam Kumar"
                        },
                        new
                        {
                            Id = 112,
                            Address = "Jaipur",
                            Name = "Ramesh Kumar"
                        },
                        new
                        {
                            Id = 113,
                            Address = "Jodhpur",
                            Name = "Sweety Kumari"
                        },
                        new
                        {
                            Id = 114,
                            Address = "Jhansi",
                            Name = "Sanjay Kumar"
                        },
                        new
                        {
                            Id = 115,
                            Address = "Mumbai",
                            Name = "Mahesh Kumar"
                        },
                        new
                        {
                            Id = 116,
                            Address = "Goa",
                            Name = "Ganesh Kumar"
                        },
                        new
                        {
                            Id = 117,
                            Address = "Ranchi",
                            Name = "Rani Kumari"
                        },
                        new
                        {
                            Id = 118,
                            Address = "Deoghar",
                            Name = "Shivam Kumar"
                        },
                        new
                        {
                            Id = 119,
                            Address = "Delhi",
                            Name = "Suresh Kumar"
                        },
                        new
                        {
                            Id = 120,
                            Address = "Delhi",
                            Name = "Sujeet Kumar"
                        },
                        new
                        {
                            Id = 121,
                            Address = "Hyderabad",
                            Name = "Zafer Ravish"
                        },
                        new
                        {
                            Id = 123,
                            Address = "Address 1",
                            Name = "User 1"
                        },
                        new
                        {
                            Id = 124,
                            Address = "Address 2",
                            Name = "User 2"
                        },
                        new
                        {
                            Id = 125,
                            Address = "Address 3",
                            Name = "User 3"
                        },
                        new
                        {
                            Id = 126,
                            Address = "Address 4",
                            Name = "User 4"
                        },
                        new
                        {
                            Id = 127,
                            Address = "Address 5",
                            Name = "User 5"
                        },
                        new
                        {
                            Id = 128,
                            Address = "Address 6",
                            Name = "User 6"
                        },
                        new
                        {
                            Id = 129,
                            Address = "Address 7",
                            Name = "User 7"
                        },
                        new
                        {
                            Id = 130,
                            Address = "Address 8",
                            Name = "User 8"
                        },
                        new
                        {
                            Id = 1,
                            Address = "Rajabagicha",
                            Name = "Najish Eqbal"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Daudnagar",
                            Name = "Danish Eqbal"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Ranchi",
                            Name = "Yasin Ekbal"
                        },
                        new
                        {
                            Id = 4,
                            Address = "MaharajGanj",
                            Name = "Taukir Khan"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Pakistan",
                            Name = "Bilal Shaeed"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
